create table tb_user (id int8 generated by default as identity, address varchar(255), birthday date, email varchar(255), name varchar(255), primary key (id));
create table tb_user_skills (user_id int8 not null, skills varchar(255));
alter table if exists tb_user_skills add constraint FKdjt3hcgsnenb1ntre5d05g02u foreign key (user_id) references tb_user;